spring.application.name=api_curd_1

spring.datasource.url=jdbc:mysql://localhost:3306/apidemo
spring.datasource.username=root
spring.datasource.password=nitin

spring.jpa.hibernate.ddl-auto=update

server.port=9090
